project:
  sys: TCP
  name: hmfb-tcp
  title: HMFB TCP

jasypt:
  encryptor:
    bean: stringEncryptor
    
spring:
  config:
    import:
    - file:${installPath}/hmfb.yml
  devtools:
    livereload:
      enabled: false

server:
  tomcat:
    uri-encoding: UTF-8
  error:
    include-exception: true
  port: 8070
  shutdown: graceful